name: Build, Test, and Generate MSI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0' # Update based on your project’s target .NET version

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore src/somefile.sln

      # Build the project
      - name: Build
        run: dotnet build src/somefile.sln --configuration Release

      # Install WiX Toolset if not already installed
      - name: Install WiX Toolset
        run: |
          if (-not (Get-Command candle.exe -ErrorAction SilentlyContinue)) {
            choco install wixtoolset --version=3.14.1 --force
          }

      # Prepare MSI using WiX
      - name: Build MSI
        run: |
          msbuild src/somefile.sln /t:Build /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=./output
          candle.exe -out ./output/yourproject.wixobj ./src/installer/yourproject.wxs
          light.exe -out ./output/SWF-Orchestrator.msi ./output/yourproject.wixobj

      # Upload the generated MSI
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: msi-package
          path: ./output/*.msi
