name: Build, Test, and Generate MSI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository to the runner's workspace
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0' # Update based on your project’s target .NET version

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Restore dependencies based on the solution file
      - name: Restore Dependencies
        run: dotnet restore ./src/somefile.sln # Update to your actual solution file path

      # Build the project using the solution file
      - name: Build
        run: dotnet build ./src/somefile.sln --configuration Release # Update to your actual solution file path

      # Run tests using the solution file
      - name: Run Tests
        run: dotnet test ./src/somefile.sln --no-build --verbosity normal # Update to your actual solution file path

      # Build the MSI package
      - name: Build MSI
        run: msbuild ./src/somefile.sln /t:Build /p:Configuration=Debug /p:Platform="Any CPU" /p:OutputPath=./output


      # Upload the generated MSI as an artifact
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: msi-package
          path: ./output/*.msi
